apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.username }}-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.username }}-db-svc"
  labels:
    app: "{{ .Chart.Name }}-db"
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: "{{ .Chart.Name }}-db"
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
